id: IAF9CB8A2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T21:20:07+00:00'
last_modified: '2022-06-09T08:37:38.729260+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17614
  title: '口述当代西藏第一

    '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8886':
      image_group_id: I4PD4237
      title: Volume 1 of 口述当代西藏第一
      total_pages: 266
      order: 1
      base_file: 8886.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
